version: 2

models:
  - name: dim_products
    columns:
      - name: product_id
        tests:
          - unique
          - not_null
  - name: dim_users
    columns:
    - name: user_id
      tests:
        - unique
        - not_null
  - name: fct_user_orders
    columns:
    - name: user_id
      tests:
        - unique
        - not_null
